### ISSUE TITLE
Does not have folder 'client' inside httptoolkit-server folder

### ISSUE THREAD

**Issue by lupohan44** [Titoot/httptoolkit-interceptor#2]
Hi, after using latest version, the patching failed due to there is no client folder inside httptoolkit-server folder.

After I tried to ignore this error and using http toolkit, seems like application is unable to start, it hang in startup anmiation.

**Comment by lupohan44** [comment]
Hang is caused by CORS

```
--- Launching HTTP Toolkit desktop v1.14.8 ---
Config checked in 47 ms
Certificates setup in 4 ms
Standalone server started in 2 ms
INFO: Initialising UI (version 0449b4219e7983cfcae0d6353032989dc594a398)
Server started in 9 ms
Total startup took 62 ms
INFO: Account store initialized
INFO: UI store initialized
INFO: Proxy settings loaded
(node:12332) Warning: Using insecure HTTP parsing
(Use `node --trace-warnings ...` to show where the warning was created)
ERROR: Access to fetch at 'http://127.0.0.1:45456/start' from origin 'http://localhost:6969' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
INFO: Server initialization failed TypeError: Failed to fetch
INFO: API store initialized
ERROR: Uncaught SyntaxError: missing ) after argument list
ERROR: Uncaught SyntaxError: missing ) after argument list
Running C:\Program Files\Java\jdk-1.8\bin\java:
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/attach/AgentLoadException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:681)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:663)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.AgentLoadException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more

Running java:
=> Java attach APIs are not available
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/attach/AgentLoadException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:681)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:663)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.AgentLoadException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more

ERROR: Access to fetch at 'http://127.0.0.1:45456/start' from origin 'http://localhost:6969' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
INFO: Server initialization failed TypeError: Failed to fetch
```

**Comment by Titoot** [comment]
Can you provide the folder structure for `httptoolkit-server` folder?
how it looks from my side (using `tree` command)
```
└───client
    ├───1.14.8
    │   ├───bin
    │   ├───bundle
 ```
and the error is expected because it only patched the asar

**Comment by lupohan44** [comment]
My tree command is not working, so the output is from dir
```
2023/12/29  22:26    <DIR>          .
2023/12/29  22:26    <DIR>          ..
2023/12/29  22:26                 0 autoupdate
2023/12/30  00:04             5,331 autoupdate.log
2023/12/29  23:03                 0 lastrun
               3 File(s)          5,331 bytes
               2 Dir(s)  388,227,473,408 bytes free
```

**Comment by Titoot** [comment]
@lupohan44 So no folders?
That's interesting, try to open something like process hacker and look for the `node.exe` process under httptoolkit and see from where it was ran or it's command line args

**Comment by lupohan44** [comment]
> @lupohan44 So no folders?

No

**Comment by lupohan44** [comment]
"C:\Users\lupohan\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bin\..\bin\node.exe"  "C:\Users\lupohan\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bin\..\bin\run" start

 Directory of C:\Users\lupohan\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bin

```
2023/12/29  23:03    <DIR>          .
2023/12/29  23:03    <DIR>          ..
2023/11/28  11:50             1,732 httptoolkit-server
2023/11/28  11:50               642 httptoolkit-server.cmd
2023/11/28  11:50        69,752,896 node.exe
2023/11/28  11:50                92 run
               4 File(s)     69,755,362 bytes
               2 Dir(s)  395,988,946,944 bytes free
```

run:
```
#!/usr/bin/env node

require('@oclif/command').run()
.catch(require('@oclif/errors/handle'))
```

**Comment by Titoot** [comment]
Ok now that makes sense, I'm outside rn when I'm back I'll create a fix for it, thanks for contributing

**Comment by Titoot** [comment]
@lupohan44 committed the changes, test it and if it works correctly I'll close the issue

**Comment by lupohan44** [comment]
patch works fine, but clicking "Settings" will cause application crash
